package cl.origen.platform.common.response;

import java.time.OffsetDateTime;

import lombok.Builder;
import lombok.Getter;

/**
 * Standard API response for all ORIGEN endpoints.
 *
 * @param <T> Payload type returned by the endpoint.
 */
@Getter
@Builder
public class Response<T> {

    /**
     * Request execution status.
     */
    private final ResponseStatus status;

    /**
     * Human-readable message.
     */
    private final String message;

    /**
     * Response payload.
     */
    private final T data;

    /**
     * UTC timestamp generated by the backend.
     */
    @Builder.Default
    private final OffsetDateTime timestamp = OffsetDateTime.now();

    /**
     * Creates a successful response.
     */
    public static <T> Response<T> ok(final T data, final String message) {
        return Response.<T>builder()
                .status(ResponseStatus.OK)
                .message(message)
                .data(data)
                .build();
    }

    /**
     * Creates an error response.
     */
    public static <T> Response<T> error(final String message) {
        return Response.<T>builder()
                .status(ResponseStatus.ERROR)
                .message(message)
                .build();
    }

}