package cl.origen.platform.common.response;

import java.time.OffsetDateTime;

import lombok.Builder;
import lombok.Getter;

/**
 * Standard API response for all ORIGEN endpoints.
 *
 * @param <T> Payload type returned by the endpoint.
 */
@Getter
@Builder
public class Response<T> {

    /**
     * Request execution status.
     */
    private final ResponseStatus status;

    /**
     * Human-readable message.
     */
    private final String message;

    /**
     * Response payload.
     */
    private final T data;

    /**
     * Timestamp generated by the backend.
     */
    private final OffsetDateTime timestamp;

}
